test:
    build: .
    command: nosetests --with-coverage --cover-package=bsAbstimmungen
    volumes:
        - ./:/src/
    working_dir: /src/
    environment:
        - LOG_CFG=tests/test-logging.json
#    links:
#        - db
# db:
#     image: mariadb
#     environment:
#         - MYSQL_ROOT_PASSWORD=1q2w3e4r
#         - MYSQL_DATABASE=bs
